[job]
dump_folder = "./outputs/demo_mae"
description = "mae training"

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 10

[metrics]
log_freq = 100
folder = "logs"

[model]
size = "2B"  # "2B" or "8B"
img_size = 512  
patch_size = 8  
mask_ratio = 0.95
crop_size = [512, 512, 512]
val_crop_size = [512, 512, 512]

[data]
dataset_folder = "/lustre/blizzard/stf218/scratch/emin/cellmap-segmentation-challenge/data"
augment = true  # whether to use "cheap" data augmentations during data loading

[optimizer]
name = "AdamW"
lr = 3e-4

[training]
batch_size = 1
warmup_steps = 1000  # lr scheduler warm up
max_norm = 1.0  # grad norm clipping
steps = 25000  # number of training steps
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 1
compile = false

[checkpoint]
enable_checkpoint = true
folder = "checkpoint"
interval_type = "steps"
interval = 5000
model_weights_only = false
export_dtype = "bfloat16"
async_mode = "disabled"  # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = 'full'  # ['none', 'selective', 'full']
selective_ac_option = 'op'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_float8_linear = false